### ISSUE TITLE
Access to detailed documentation

### ISSUE THREAD

**Issue by supernifty** [eilslabs/DKFZBiasFilter#10]
The provided link: https://wiki.oicr.on.ca/display/PANCANCER/DKFZ+SNV+bias+filtering?preview=/66951525/66952026/description_dkfz_bias_filter.pdf is not public access and requires an OICR login.

**Comment by buchhalt** [comment]
Sorry, here is the file:
[description_dkfz_bias_filter.pdf](https://github.com/eilslabs/DKFZBiasFilter/files/2075862/description_dkfz_bias_filter.pdf)

**Comment by supernifty** [comment]
Thanks @buchhalt !
