### ISSUE TITLE
Methods description?

### ISSUE THREAD

**Issue by sigven** [eilslabs/DKFZBiasFilter#6]
Hi,

Would it be possible to provide the detailed methods description in a folder that is publicly accessible (the link you provide to wiki.oicr.on.ca requires a username/password)?

best,
Sigve

**Comment by sigven** [comment]
dear @chapmanb, @buchhalt, @jwerner-dkfz 
Is anyone of you able to point us to a public description of the DKFZBiasFilter (see issue above)?

**Comment by chapmanb** [comment]
I'm not on the DKFZ team, only a happy user of the tool, so don't have access. +1 from me that it would be great to have more public inofmration about the methods.

**Comment by jwerner-dkfz** [comment]
With tag 1.2.3 (commit hash a486939),  a [description](https://github.com/eilslabs/DKFZBiasFilter/blob/master/description_dkfz_bias_filter.pdf) has been added.
